<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCitiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cities', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedInteger('province_id')->index();
            $table->string('name', 60);
            $table->string('type', 15);
            $table->index('name', 'type');
            $table->timestamps();

            $table->foreign('province_id')
              ->references('id')->on('provinces')
              ->onDelete('restrict');
        });

        DB::table('cities')->insert([
            ['id' => 1, 'province_id' => 1, 'name' => 'Aceh Barat', 'type' => 'kabupaten'],
['id' => 2, 'province_id' => 1, 'name' => 'Aceh Barat Daya', 'type' => 'kabupaten'],
['id' => 3, 'province_id' => 1, 'name' => 'Aceh Besar', 'type' => 'kabupaten'],
['id' => 4, 'province_id' => 1, 'name' => 'Aceh Jaya', 'type' => 'kabupaten'],
['id' => 5, 'province_id' => 1, 'name' => 'Aceh Selatan', 'type' => 'kabupaten'],
['id' => 6, 'province_id' => 1, 'name' => 'Aceh Singkil', 'type' => 'kabupaten'],
['id' => 7, 'province_id' => 1, 'name' => 'Aceh Tamiang', 'type' => 'kabupaten'],
['id' => 8, 'province_id' => 1, 'name' => 'Aceh Tengah', 'type' => 'kabupaten'],
['id' => 9, 'province_id' => 1, 'name' => 'Aceh Tenggara', 'type' => 'kabupaten'],
['id' => 10, 'province_id' => 1, 'name' => 'Aceh Timur', 'type' => 'kabupaten'],
['id' => 11, 'province_id' => 1, 'name' => 'Aceh Utara', 'type' => 'kabupaten'],
['id' => 12, 'province_id' => 1, 'name' => 'Bener Meriah', 'type' => 'kabupaten'],
['id' => 13, 'province_id' => 1, 'name' => 'Bireuen', 'type' => 'kabupaten'],
['id' => 14, 'province_id' => 1, 'name' => 'Gayo Luwes', 'type' => 'kabupaten'],
['id' => 15, 'province_id' => 1, 'name' => 'Nagan Raya', 'type' => 'kabupaten'],
['id' => 16, 'province_id' => 1, 'name' => 'Pidie', 'type' => 'kabupaten'],
['id' => 17, 'province_id' => 1, 'name' => 'Pidie Jaya', 'type' => 'kabupaten'],
['id' => 18, 'province_id' => 1, 'name' => 'Simeulue', 'type' => 'kabupaten'],
['id' => 19, 'province_id' => 1, 'name' => 'Banda Aceh', 'type' => 'kota'],
['id' => 20, 'province_id' => 1, 'name' => 'Langsa', 'type' => 'kota'],
['id' => 21, 'province_id' => 1, 'name' => 'Lhokseumawe', 'type' => 'kota'],
['id' => 22, 'province_id' => 1, 'name' => 'Sabang', 'type' => 'kota'],
['id' => 23, 'province_id' => 1, 'name' => 'Subulussalam', 'type' => 'kota'],
['id' => 24, 'province_id' => 2, 'name' => 'Asahan', 'type' => 'kabupaten'],
['id' => 25, 'province_id' => 2, 'name' => 'Batubara', 'type' => 'kabupaten'],
['id' => 26, 'province_id' => 2, 'name' => 'Dairi', 'type' => 'kabupaten'],
['id' => 27, 'province_id' => 2, 'name' => 'Deli Serdang', 'type' => 'kabupaten'],
['id' => 28, 'province_id' => 2, 'name' => 'Humbang Hasundutan', 'type' => 'kabupaten'],
['id' => 29, 'province_id' => 2, 'name' => 'Karo', 'type' => 'kabupaten'],
['id' => 30, 'province_id' => 2, 'name' => 'Labuhan Batu', 'type' => 'kabupaten'],
['id' => 31, 'province_id' => 2, 'name' => 'Labuhanbatu Selatan', 'type' => 'kabupaten'],
['id' => 32, 'province_id' => 2, 'name' => 'Labuhanbatu Utara', 'type' => 'kabupaten'],
['id' => 33, 'province_id' => 2, 'name' => 'Langkat', 'type' => 'kabupaten'],
['id' => 34, 'province_id' => 2, 'name' => 'Mandailing Natal', 'type' => 'kabupaten'],
['id' => 35, 'province_id' => 2, 'name' => 'Nias', 'type' => 'kabupaten'],
['id' => 36, 'province_id' => 2, 'name' => 'Nias Barat', 'type' => 'kabupaten'],
['id' => 37, 'province_id' => 2, 'name' => 'Nias Selatan', 'type' => 'kabupaten'],
['id' => 38, 'province_id' => 2, 'name' => 'Nias Utara', 'type' => 'kabupaten'],
['id' => 39, 'province_id' => 2, 'name' => 'Padang Lawas', 'type' => 'kabupaten'],
['id' => 40, 'province_id' => 2, 'name' => 'Padang Lawas Utara', 'type' => 'kabupaten'],
['id' => 41, 'province_id' => 2, 'name' => 'Pakpak Barat', 'type' => 'kabupaten'],
['id' => 42, 'province_id' => 2, 'name' => 'Samosir', 'type' => 'kabupaten'],
['id' => 43, 'province_id' => 2, 'name' => 'Serdang Bedagai', 'type' => 'kabupaten'],
['id' => 44, 'province_id' => 2, 'name' => 'Simalungun', 'type' => 'kabupaten'],
['id' => 45, 'province_id' => 2, 'name' => 'Tapanuli Selatan', 'type' => 'kabupaten'],
['id' => 46, 'province_id' => 2, 'name' => 'Tapanuli Tengah', 'type' => 'kabupaten'],
['id' => 47, 'province_id' => 2, 'name' => 'Tapanuli Utara', 'type' => 'kabupaten'],
['id' => 48, 'province_id' => 2, 'name' => 'Toba Samosir', 'type' => 'kabupaten'],
['id' => 49, 'province_id' => 2, 'name' => 'Binjai', 'type' => 'kota'],
['id' => 50, 'province_id' => 2, 'name' => 'Gunung Sitoli', 'type' => 'kota'],
['id' => 51, 'province_id' => 2, 'name' => 'Medan', 'type' => 'kota'],
['id' => 52, 'province_id' => 2, 'name' => 'Padangsidempuan', 'type' => 'kota'],
['id' => 53, 'province_id' => 2, 'name' => 'Pematang Siantar', 'type' => 'kota'],
['id' => 54, 'province_id' => 2, 'name' => 'Sibolga', 'type' => 'kota'],
['id' => 55, 'province_id' => 2, 'name' => 'Tanjung Balai', 'type' => 'kota'],
['id' => 56, 'province_id' => 2, 'name' => 'Tebing Tinggi', 'type' => 'kota'],
['id' => 57, 'province_id' => 3, 'name' => 'Agam', 'type' => 'kabupaten'],
['id' => 58, 'province_id' => 3, 'name' => 'Dharmas Raya', 'type' => 'kabupaten'],
['id' => 59, 'province_id' => 3, 'name' => 'Kepulauan Mentawai', 'type' => 'kabupaten'],
['id' => 60, 'province_id' => 3, 'name' => 'Lima Puluh Kota', 'type' => 'kabupaten'],
['id' => 61, 'province_id' => 3, 'name' => 'Padang Pariaman', 'type' => 'kabupaten'],
['id' => 62, 'province_id' => 3, 'name' => 'Pasaman', 'type' => 'kabupaten'],
['id' => 63, 'province_id' => 3, 'name' => 'Pasaman Barat', 'type' => 'kabupaten'],
['id' => 64, 'province_id' => 3, 'name' => 'Pesisir Selatan', 'type' => 'kabupaten'],
['id' => 65, 'province_id' => 3, 'name' => 'Sijunjung', 'type' => 'kabupaten'],
['id' => 66, 'province_id' => 3, 'name' => 'Solok', 'type' => 'kabupaten'],
['id' => 67, 'province_id' => 3, 'name' => 'Solok Selatan', 'type' => 'kabupaten'],
['id' => 68, 'province_id' => 3, 'name' => 'Tanah Datar', 'type' => 'kabupaten'],
['id' => 69, 'province_id' => 3, 'name' => 'Bukittinggi', 'type' => 'kota'],
['id' => 70, 'province_id' => 3, 'name' => 'Padang', 'type' => 'kota'],
['id' => 71, 'province_id' => 3, 'name' => 'Padang Panjang', 'type' => 'kota'],
['id' => 72, 'province_id' => 3, 'name' => 'Pariaman', 'type' => 'kota'],
['id' => 73, 'province_id' => 3, 'name' => 'Payakumbuh', 'type' => 'kota'],
['id' => 74, 'province_id' => 3, 'name' => 'Sawah Lunto', 'type' => 'kota'],
['id' => 75, 'province_id' => 3, 'name' => 'Solok', 'type' => 'kota'],
['id' => 76, 'province_id' => 4, 'name' => 'Bengkalis', 'type' => 'kabupaten'],
['id' => 77, 'province_id' => 4, 'name' => 'Indragiri Hilir', 'type' => 'kabupaten'],
['id' => 78, 'province_id' => 4, 'name' => 'Indragiri Hulu', 'type' => 'kabupaten'],
['id' => 79, 'province_id' => 4, 'name' => 'Kampar', 'type' => 'kabupaten'],
['id' => 80, 'province_id' => 4, 'name' => 'Kuantan Singingi', 'type' => 'kabupaten'],
['id' => 81, 'province_id' => 4, 'name' => 'Meranti', 'type' => 'kabupaten'],
['id' => 82, 'province_id' => 4, 'name' => 'Pelalawan', 'type' => 'kabupaten'],
['id' => 83, 'province_id' => 4, 'name' => 'Rokan Hilir', 'type' => 'kabupaten'],
['id' => 84, 'province_id' => 4, 'name' => 'Rokan Hulu', 'type' => 'kabupaten'],
['id' => 85, 'province_id' => 4, 'name' => 'Siak', 'type' => 'kabupaten'],
['id' => 86, 'province_id' => 4, 'name' => 'Dumai', 'type' => 'kota'],
['id' => 87, 'province_id' => 4, 'name' => 'Pekanbaru', 'type' => 'kota'],
['id' => 88, 'province_id' => 5, 'name' => 'Bintan', 'type' => 'kabupaten'],
['id' => 89, 'province_id' => 5, 'name' => 'Karimun', 'type' => 'kabupaten'],
['id' => 90, 'province_id' => 5, 'name' => 'Kepulauan Anambas', 'type' => 'kabupaten'],
['id' => 91, 'province_id' => 5, 'name' => 'Lingga', 'type' => 'kabupaten'],
['id' => 92, 'province_id' => 5, 'name' => 'Natuna', 'type' => 'kabupaten'],
['id' => 93, 'province_id' => 5, 'name' => 'Batam', 'type' => 'kota'],
['id' => 94, 'province_id' => 5, 'name' => 'Tanjung Pinang', 'type' => 'kota'],
['id' => 95, 'province_id' => 6, 'name' => 'Bangka', 'type' => 'kabupaten'],
['id' => 96, 'province_id' => 6, 'name' => 'Bangka Barat', 'type' => 'kabupaten'],
['id' => 97, 'province_id' => 6, 'name' => 'Bangka Selatan', 'type' => 'kabupaten'],
['id' => 98, 'province_id' => 6, 'name' => 'Bangka Tengah', 'type' => 'kabupaten'],
['id' => 99, 'province_id' => 6, 'name' => 'Belitung', 'type' => 'kabupaten'],
['id' => 100, 'province_id' => 6, 'name' => 'Belitung Timur', 'type' => 'kabupaten'],
['id' => 101, 'province_id' => 6, 'name' => 'Pangkal Pinang', 'type' => 'kota'],
['id' => 102, 'province_id' => 7, 'name' => 'Kerinci', 'type' => 'kabupaten'],
['id' => 103, 'province_id' => 7, 'name' => 'Merangin', 'type' => 'kabupaten'],
['id' => 104, 'province_id' => 7, 'name' => 'Sarolangun', 'type' => 'kabupaten'],
['id' => 105, 'province_id' => 7, 'name' => 'Batang Hari', 'type' => 'kabupaten'],
['id' => 106, 'province_id' => 7, 'name' => 'Muaro Jambi', 'type' => 'kabupaten'],
['id' => 107, 'province_id' => 7, 'name' => 'Tanjung Jabung Timur', 'type' => 'kabupaten'],
['id' => 108, 'province_id' => 7, 'name' => 'Tanjung Jabung Barat', 'type' => 'kabupaten'],
['id' => 109, 'province_id' => 7, 'name' => 'Tebo', 'type' => 'kabupaten'],
['id' => 110, 'province_id' => 7, 'name' => 'Bungo', 'type' => 'kabupaten'],
['id' => 111, 'province_id' => 7, 'name' => 'Jambi', 'type' => 'kota'],
['id' => 112, 'province_id' => 7, 'name' => 'Sungai Penuh', 'type' => 'kota'],
['id' => 113, 'province_id' => 8, 'name' => 'Bengkulu Selatan', 'type' => 'kabupaten'],
['id' => 114, 'province_id' => 8, 'name' => 'Bengkulu Tengah', 'type' => 'kabupaten'],
['id' => 115, 'province_id' => 8, 'name' => 'Bengkulu Utara', 'type' => 'kabupaten'],
['id' => 116, 'province_id' => 8, 'name' => 'Kaur', 'type' => 'kabupaten'],
['id' => 117, 'province_id' => 8, 'name' => 'Kepahiang', 'type' => 'kabupaten'],
['id' => 118, 'province_id' => 8, 'name' => 'Lebong', 'type' => 'kabupaten'],
['id' => 119, 'province_id' => 8, 'name' => 'Mukomuko', 'type' => 'kabupaten'],
['id' => 120, 'province_id' => 8, 'name' => 'Rejang Lebong', 'type' => 'kabupaten'],
['id' => 121, 'province_id' => 8, 'name' => 'Seluma', 'type' => 'kabupaten'],
['id' => 122, 'province_id' => 8, 'name' => 'Bengkulu', 'type' => 'kota'],
['id' => 123, 'province_id' => 9, 'name' => 'Banyuasin', 'type' => 'kabupaten'],
['id' => 124, 'province_id' => 9, 'name' => 'Empat Lawang', 'type' => 'kabupaten'],
['id' => 125, 'province_id' => 9, 'name' => 'Lahat', 'type' => 'kabupaten'],
['id' => 126, 'province_id' => 9, 'name' => 'Muara Enim', 'type' => 'kabupaten'],
['id' => 127, 'province_id' => 9, 'name' => 'Musi Banyu Asin', 'type' => 'kabupaten'],
['id' => 128, 'province_id' => 9, 'name' => 'Musi Rawas', 'type' => 'kabupaten'],
['id' => 129, 'province_id' => 9, 'name' => 'Ogan Ilir', 'type' => 'kabupaten'],
['id' => 130, 'province_id' => 9, 'name' => 'Ogan Komering Ilir', 'type' => 'kabupaten'],
['id' => 131, 'province_id' => 9, 'name' => 'Ogan Komering Ulu', 'type' => 'kabupaten'],
['id' => 132, 'province_id' => 9, 'name' => 'Ogan Komering Ulu Se', 'type' => 'kabupaten'],
['id' => 133, 'province_id' => 9, 'name' => 'Ogan Komering Ulu Ti', 'type' => 'kabupaten'],
['id' => 134, 'province_id' => 9, 'name' => 'Lubuklinggau', 'type' => 'kota'],
['id' => 135, 'province_id' => 9, 'name' => 'Pagar Alam', 'type' => 'kota'],
['id' => 136, 'province_id' => 9, 'name' => 'Palembang', 'type' => 'kota'],
['id' => 137, 'province_id' => 9, 'name' => 'Prabumulih', 'type' => 'kota'],
['id' => 138, 'province_id' => 10, 'name' => 'Lampung Barat', 'type' => 'kabupaten'],
['id' => 139, 'province_id' => 10, 'name' => 'Lampung Selatan', 'type' => 'kabupaten'],
['id' => 140, 'province_id' => 10, 'name' => 'Lampung Tengah', 'type' => 'kabupaten'],
['id' => 141, 'province_id' => 10, 'name' => 'Lampung Timur', 'type' => 'kabupaten'],
['id' => 142, 'province_id' => 10, 'name' => 'Lampung Utara', 'type' => 'kabupaten'],
['id' => 143, 'province_id' => 10, 'name' => 'Mesuji', 'type' => 'kabupaten'],
['id' => 144, 'province_id' => 10, 'name' => 'Pesawaran', 'type' => 'kabupaten'],
['id' => 145, 'province_id' => 10, 'name' => 'Pringsewu', 'type' => 'kabupaten'],
['id' => 146, 'province_id' => 10, 'name' => 'Tanggamus', 'type' => 'kabupaten'],
['id' => 147, 'province_id' => 10, 'name' => 'Tulang Bawang', 'type' => 'kabupaten'],
['id' => 148, 'province_id' => 10, 'name' => 'Tulang Bawang Barat', 'type' => 'kabupaten'],
['id' => 149, 'province_id' => 10, 'name' => 'Way Kanan', 'type' => 'kabupaten'],
['id' => 150, 'province_id' => 10, 'name' => 'Bandar Lampung', 'type' => 'kota'],
['id' => 151, 'province_id' => 10, 'name' => 'Metro', 'type' => 'kota'],
['id' => 152, 'province_id' => 11, 'name' => 'Lebak', 'type' => 'kabupaten'],
['id' => 153, 'province_id' => 11, 'name' => 'Pandeglang', 'type' => 'kabupaten'],
['id' => 154, 'province_id' => 11, 'name' => 'Serang', 'type' => 'kabupaten'],
['id' => 155, 'province_id' => 11, 'name' => 'Tangerang', 'type' => 'kabupaten'],
['id' => 156, 'province_id' => 11, 'name' => 'Cilegon', 'type' => 'kota'],
['id' => 157, 'province_id' => 11, 'name' => 'Serang', 'type' => 'kota'],
['id' => 158, 'province_id' => 11, 'name' => 'Tangerang', 'type' => 'kota'],
['id' => 159, 'province_id' => 11, 'name' => 'Tangerang Selatan', 'type' => 'kota'],
['id' => 160, 'province_id' => 12, 'name' => 'Adm. Kepulauan Serib', 'type' => 'kabupaten'],
['id' => 161, 'province_id' => 12, 'name' => 'Jakarta Barat', 'type' => 'kota'],
['id' => 162, 'province_id' => 12, 'name' => 'Jakarta Pusat', 'type' => 'kota'],
['id' => 163, 'province_id' => 12, 'name' => 'Jakarta Selatan', 'type' => 'kota'],
['id' => 164, 'province_id' => 12, 'name' => 'Jakarta Timur', 'type' => 'kota'],
['id' => 165, 'province_id' => 12, 'name' => 'Jakarta Utara', 'type' => 'kota'],
['id' => 166, 'province_id' => 13, 'name' => 'Bandung', 'type' => 'kabupaten'],
['id' => 167, 'province_id' => 13, 'name' => 'Bandung Barat', 'type' => 'kabupaten'],
['id' => 168, 'province_id' => 13, 'name' => 'Bekasi', 'type' => 'kabupaten'],
['id' => 169, 'province_id' => 13, 'name' => 'Bogor', 'type' => 'kabupaten'],
['id' => 170, 'province_id' => 13, 'name' => 'Ciamis', 'type' => 'kabupaten'],
['id' => 171, 'province_id' => 13, 'name' => 'Cianjur', 'type' => 'kabupaten'],
['id' => 172, 'province_id' => 13, 'name' => 'Cirebon', 'type' => 'kabupaten'],
['id' => 173, 'province_id' => 13, 'name' => 'Garut', 'type' => 'kabupaten'],
['id' => 174, 'province_id' => 13, 'name' => 'Indramayu', 'type' => 'kabupaten'],
['id' => 175, 'province_id' => 13, 'name' => 'Karawang', 'type' => 'kabupaten'],
['id' => 176, 'province_id' => 13, 'name' => 'Kuningan', 'type' => 'kabupaten'],
['id' => 177, 'province_id' => 13, 'name' => 'Majalengka', 'type' => 'kabupaten'],
['id' => 178, 'province_id' => 13, 'name' => 'Purwakarta', 'type' => 'kabupaten'],
['id' => 179, 'province_id' => 13, 'name' => 'Subang', 'type' => 'kabupaten'],
['id' => 180, 'province_id' => 13, 'name' => 'Sukabumi', 'type' => 'kabupaten'],
['id' => 181, 'province_id' => 13, 'name' => 'Sumedang', 'type' => 'kabupaten'],
['id' => 182, 'province_id' => 13, 'name' => 'Tasikmalaya', 'type' => 'kabupaten'],
['id' => 183, 'province_id' => 13, 'name' => 'Bandung', 'type' => 'kota'],
['id' => 184, 'province_id' => 13, 'name' => 'Banjar', 'type' => 'kota'],
['id' => 185, 'province_id' => 13, 'name' => 'Bekasi', 'type' => 'kota'],
['id' => 186, 'province_id' => 13, 'name' => 'Bogor', 'type' => 'kota'],
['id' => 187, 'province_id' => 13, 'name' => 'Cimahi', 'type' => 'kota'],
['id' => 188, 'province_id' => 13, 'name' => 'Cirebon', 'type' => 'kota'],
['id' => 189, 'province_id' => 13, 'name' => 'Depok', 'type' => 'kota'],
['id' => 190, 'province_id' => 13, 'name' => 'Sukabumi', 'type' => 'kota'],
['id' => 191, 'province_id' => 13, 'name' => 'Tasikmalaya', 'type' => 'kota'],
['id' => 192, 'province_id' => 14, 'name' => 'Banjarnegara', 'type' => 'kabupaten'],
['id' => 193, 'province_id' => 14, 'name' => 'Banyumas', 'type' => 'kabupaten'],
['id' => 194, 'province_id' => 14, 'name' => 'Batang', 'type' => 'kabupaten'],
['id' => 195, 'province_id' => 14, 'name' => 'Blora', 'type' => 'kabupaten'],
['id' => 196, 'province_id' => 14, 'name' => 'Boyolali', 'type' => 'kabupaten'],
['id' => 197, 'province_id' => 14, 'name' => 'Brebes', 'type' => 'kabupaten'],
['id' => 198, 'province_id' => 14, 'name' => 'Cilacap', 'type' => 'kabupaten'],
['id' => 199, 'province_id' => 14, 'name' => 'Demak', 'type' => 'kabupaten'],
['id' => 200, 'province_id' => 14, 'name' => 'Grobogan', 'type' => 'kabupaten'],
['id' => 201, 'province_id' => 14, 'name' => 'Jepara', 'type' => 'kabupaten'],
['id' => 202, 'province_id' => 14, 'name' => 'Karanganyar', 'type' => 'kabupaten'],
['id' => 203, 'province_id' => 14, 'name' => 'Kebumen', 'type' => 'kabupaten'],
['id' => 204, 'province_id' => 14, 'name' => 'Kendal', 'type' => 'kabupaten'],
['id' => 205, 'province_id' => 14, 'name' => 'Klaten', 'type' => 'kabupaten'],
['id' => 206, 'province_id' => 14, 'name' => 'Kota Tegal', 'type' => 'kabupaten'],
['id' => 207, 'province_id' => 14, 'name' => 'Kudus', 'type' => 'kabupaten'],
['id' => 208, 'province_id' => 14, 'name' => 'Magelang', 'type' => 'kabupaten'],
['id' => 209, 'province_id' => 14, 'name' => 'Pati', 'type' => 'kabupaten'],
['id' => 210, 'province_id' => 14, 'name' => 'Pekalongan', 'type' => 'kabupaten'],
['id' => 211, 'province_id' => 14, 'name' => 'Pemalang', 'type' => 'kabupaten'],
['id' => 212, 'province_id' => 14, 'name' => 'Purbalingga', 'type' => 'kabupaten'],
['id' => 213, 'province_id' => 14, 'name' => 'Purworejo', 'type' => 'kabupaten'],
['id' => 214, 'province_id' => 14, 'name' => 'Rembang', 'type' => 'kabupaten'],
['id' => 215, 'province_id' => 14, 'name' => 'Semarang', 'type' => 'kabupaten'],
['id' => 216, 'province_id' => 14, 'name' => 'Sragen', 'type' => 'kabupaten'],
['id' => 217, 'province_id' => 14, 'name' => 'Sukoharjo', 'type' => 'kabupaten'],
['id' => 218, 'province_id' => 14, 'name' => 'Temanggung', 'type' => 'kabupaten'],
['id' => 219, 'province_id' => 14, 'name' => 'Wonogiri', 'type' => 'kabupaten'],
['id' => 220, 'province_id' => 14, 'name' => 'Wonosobo', 'type' => 'kabupaten'],
['id' => 221, 'province_id' => 14, 'name' => 'Magelang', 'type' => 'kota'],
['id' => 222, 'province_id' => 14, 'name' => 'Pekalongan', 'type' => 'kota'],
['id' => 223, 'province_id' => 14, 'name' => 'Salatiga', 'type' => 'kota'],
['id' => 224, 'province_id' => 14, 'name' => 'Semarang', 'type' => 'kota'],
['id' => 225, 'province_id' => 14, 'name' => 'Surakarta', 'type' => 'kota'],
['id' => 226, 'province_id' => 14, 'name' => 'Tegal', 'type' => 'kota'],
['id' => 227, 'province_id' => 15, 'name' => 'Bantul', 'type' => 'kabupaten'],
['id' => 228, 'province_id' => 15, 'name' => 'Gunung Kidul', 'type' => 'kabupaten'],
['id' => 229, 'province_id' => 15, 'name' => 'Kulon Progo', 'type' => 'kabupaten'],
['id' => 230, 'province_id' => 15, 'name' => 'Sleman', 'type' => 'kabupaten'],
['id' => 231, 'province_id' => 15, 'name' => 'Yogyakarta', 'type' => 'kota'],
['id' => 232, 'province_id' => 16, 'name' => 'Bangkalan', 'type' => 'kabupaten'],
['id' => 233, 'province_id' => 16, 'name' => 'Banyuwangi', 'type' => 'kabupaten'],
['id' => 234, 'province_id' => 16, 'name' => 'Blitar', 'type' => 'kabupaten'],
['id' => 235, 'province_id' => 16, 'name' => 'Bojonegoro', 'type' => 'kabupaten'],
['id' => 236, 'province_id' => 16, 'name' => 'Bondowoso', 'type' => 'kabupaten'],
['id' => 237, 'province_id' => 16, 'name' => 'Gresik', 'type' => 'kabupaten'],
['id' => 238, 'province_id' => 16, 'name' => 'Jember', 'type' => 'kabupaten'],
['id' => 239, 'province_id' => 16, 'name' => 'Jombang', 'type' => 'kabupaten'],
['id' => 240, 'province_id' => 16, 'name' => 'Kediri', 'type' => 'kabupaten'],
['id' => 241, 'province_id' => 16, 'name' => 'Lamongan', 'type' => 'kabupaten'],
['id' => 242, 'province_id' => 16, 'name' => 'Lumajang', 'type' => 'kabupaten'],
['id' => 243, 'province_id' => 16, 'name' => 'Madiun', 'type' => 'kabupaten'],
['id' => 244, 'province_id' => 16, 'name' => 'Magetan', 'type' => 'kabupaten'],
['id' => 245, 'province_id' => 16, 'name' => 'Malang', 'type' => 'kabupaten'],
['id' => 246, 'province_id' => 16, 'name' => 'Mojokerto', 'type' => 'kabupaten'],
['id' => 247, 'province_id' => 16, 'name' => 'Nganjuk', 'type' => 'kabupaten'],
['id' => 248, 'province_id' => 16, 'name' => 'Ngawi', 'type' => 'kabupaten'],
['id' => 249, 'province_id' => 16, 'name' => 'Pacitan', 'type' => 'kabupaten'],
['id' => 250, 'province_id' => 16, 'name' => 'Pamekasan', 'type' => 'kabupaten'],
['id' => 251, 'province_id' => 16, 'name' => 'Pasuruan', 'type' => 'kabupaten'],
['id' => 252, 'province_id' => 16, 'name' => 'Ponorogo', 'type' => 'kabupaten'],
['id' => 253, 'province_id' => 16, 'name' => 'Probolinggo', 'type' => 'kabupaten'],
['id' => 254, 'province_id' => 16, 'name' => 'Sampang', 'type' => 'kabupaten'],
['id' => 255, 'province_id' => 16, 'name' => 'Sidoarjo', 'type' => 'kabupaten'],
['id' => 256, 'province_id' => 16, 'name' => 'Situbondo', 'type' => 'kabupaten'],
['id' => 257, 'province_id' => 16, 'name' => 'Sumenep', 'type' => 'kabupaten'],
['id' => 258, 'province_id' => 16, 'name' => 'Trenggalek', 'type' => 'kabupaten'],
['id' => 259, 'province_id' => 16, 'name' => 'Tuban', 'type' => 'kabupaten'],
['id' => 260, 'province_id' => 16, 'name' => 'Tulungagung', 'type' => 'kabupaten'],
['id' => 261, 'province_id' => 16, 'name' => 'Batu', 'type' => 'kota'],
['id' => 262, 'province_id' => 16, 'name' => 'Blitar', 'type' => 'kota'],
['id' => 263, 'province_id' => 16, 'name' => 'Kediri', 'type' => 'kota'],
['id' => 264, 'province_id' => 16, 'name' => 'Madiun', 'type' => 'kota'],
['id' => 265, 'province_id' => 16, 'name' => 'Malang', 'type' => 'kota'],
['id' => 266, 'province_id' => 16, 'name' => 'Mojokerto', 'type' => 'kota'],
['id' => 267, 'province_id' => 16, 'name' => 'Pasuruan', 'type' => 'kota'],
['id' => 268, 'province_id' => 16, 'name' => 'Probolinggo', 'type' => 'kota'],
['id' => 269, 'province_id' => 16, 'name' => 'Surabaya', 'type' => 'kota'],
['id' => 270, 'province_id' => 17, 'name' => 'Badung', 'type' => 'kabupaten'],
['id' => 271, 'province_id' => 17, 'name' => 'Bangli', 'type' => 'kabupaten'],
['id' => 272, 'province_id' => 17, 'name' => 'Buleleng', 'type' => 'kabupaten'],
['id' => 273, 'province_id' => 17, 'name' => 'Gianyar', 'type' => 'kabupaten'],
['id' => 274, 'province_id' => 17, 'name' => 'Jembrana', 'type' => 'kabupaten'],
['id' => 275, 'province_id' => 17, 'name' => 'Karang Asem', 'type' => 'kabupaten'],
['id' => 276, 'province_id' => 17, 'name' => 'Klungkung', 'type' => 'kabupaten'],
['id' => 277, 'province_id' => 17, 'name' => 'Tabanan', 'type' => 'kabupaten'],
['id' => 278, 'province_id' => 17, 'name' => 'Denpasar', 'type' => 'kota'],
['id' => 279, 'province_id' => 18, 'name' => 'Bima', 'type' => 'kabupaten'],
['id' => 280, 'province_id' => 18, 'name' => 'Dompu', 'type' => 'kabupaten'],
['id' => 281, 'province_id' => 18, 'name' => 'Lombok Barat', 'type' => 'kabupaten'],
['id' => 282, 'province_id' => 18, 'name' => 'Lombok Tengah', 'type' => 'kabupaten'],
['id' => 283, 'province_id' => 18, 'name' => 'Lombok Timur', 'type' => 'kabupaten'],
['id' => 284, 'province_id' => 18, 'name' => 'Lombok Utara', 'type' => 'kabupaten'],
['id' => 285, 'province_id' => 18, 'name' => 'Sumbawa', 'type' => 'kabupaten'],
['id' => 286, 'province_id' => 18, 'name' => 'Sumbawa Barat', 'type' => 'kabupaten'],
['id' => 287, 'province_id' => 18, 'name' => 'Bima', 'type' => 'kota'],
['id' => 288, 'province_id' => 18, 'name' => 'Mataram', 'type' => 'kota'],
['id' => 289, 'province_id' => 19, 'name' => 'Alor', 'type' => 'kabupaten'],
['id' => 290, 'province_id' => 19, 'name' => 'Belu', 'type' => 'kabupaten'],
['id' => 291, 'province_id' => 19, 'name' => 'Ende', 'type' => 'kabupaten'],
['id' => 292, 'province_id' => 19, 'name' => 'Flores Timur', 'type' => 'kabupaten'],
['id' => 293, 'province_id' => 19, 'name' => 'Kupang', 'type' => 'kabupaten'],
['id' => 294, 'province_id' => 19, 'name' => 'Lembata', 'type' => 'kabupaten'],
['id' => 295, 'province_id' => 19, 'name' => 'Manggarai', 'type' => 'kabupaten'],
['id' => 296, 'province_id' => 19, 'name' => 'Manggarai Barat', 'type' => 'kabupaten'],
['id' => 297, 'province_id' => 19, 'name' => 'Manggarai Timur', 'type' => 'kabupaten'],
['id' => 298, 'province_id' => 19, 'name' => 'Nagekeo', 'type' => 'kabupaten'],
['id' => 299, 'province_id' => 19, 'name' => 'Ngada', 'type' => 'kabupaten'],
['id' => 300, 'province_id' => 19, 'name' => 'Rote Ndao', 'type' => 'kabupaten'],
['id' => 301, 'province_id' => 19, 'name' => 'Sabu Raijua', 'type' => 'kabupaten'],
['id' => 302, 'province_id' => 19, 'name' => 'Sikka', 'type' => 'kabupaten'],
['id' => 303, 'province_id' => 19, 'name' => 'Sumba Barat', 'type' => 'kabupaten'],
['id' => 304, 'province_id' => 19, 'name' => 'Sumba Barat Daya', 'type' => 'kabupaten'],
['id' => 305, 'province_id' => 19, 'name' => 'Sumba Tengah', 'type' => 'kabupaten'],
['id' => 306, 'province_id' => 19, 'name' => 'Sumba Timur', 'type' => 'kabupaten'],
['id' => 307, 'province_id' => 19, 'name' => 'Timor Tengah Selatan', 'type' => 'kabupaten'],
['id' => 308, 'province_id' => 19, 'name' => 'Timor Tengah Utara', 'type' => 'kabupaten'],
['id' => 309, 'province_id' => 19, 'name' => 'Kupang', 'type' => 'kota'],
['id' => 310, 'province_id' => 20, 'name' => 'Bengkayang', 'type' => 'kabupaten'],
['id' => 311, 'province_id' => 20, 'name' => 'Kapuas Hulu', 'type' => 'kabupaten'],
['id' => 312, 'province_id' => 20, 'name' => 'Kayong Utara', 'type' => 'kabupaten'],
['id' => 313, 'province_id' => 20, 'name' => 'Ketapang', 'type' => 'kabupaten'],
['id' => 314, 'province_id' => 20, 'name' => 'Kubu Raya', 'type' => 'kabupaten'],
['id' => 315, 'province_id' => 20, 'name' => 'Landak', 'type' => 'kabupaten'],
['id' => 316, 'province_id' => 20, 'name' => 'Melawi', 'type' => 'kabupaten'],
['id' => 317, 'province_id' => 20, 'name' => 'Pontianak', 'type' => 'kabupaten'],
['id' => 318, 'province_id' => 20, 'name' => 'Sambas', 'type' => 'kabupaten'],
['id' => 319, 'province_id' => 20, 'name' => 'Sanggau', 'type' => 'kabupaten'],
['id' => 320, 'province_id' => 20, 'name' => 'Sekadau', 'type' => 'kabupaten'],
['id' => 321, 'province_id' => 20, 'name' => 'Sintang', 'type' => 'kabupaten'],
['id' => 322, 'province_id' => 20, 'name' => 'Pontianak', 'type' => 'kota'],
['id' => 323, 'province_id' => 20, 'name' => 'Singkawang', 'type' => 'kota'],
['id' => 324, 'province_id' => 21, 'name' => 'Barito Selatan', 'type' => 'kabupaten'],
['id' => 325, 'province_id' => 21, 'name' => 'Barito Timur', 'type' => 'kabupaten'],
['id' => 326, 'province_id' => 21, 'name' => 'Barito Utara', 'type' => 'kabupaten'],
['id' => 327, 'province_id' => 21, 'name' => 'Gunung Mas', 'type' => 'kabupaten'],
['id' => 328, 'province_id' => 21, 'name' => 'Kapuas', 'type' => 'kabupaten'],
['id' => 329, 'province_id' => 21, 'name' => 'Katingan', 'type' => 'kabupaten'],
['id' => 330, 'province_id' => 21, 'name' => 'Kotawaringin Barat', 'type' => 'kabupaten'],
['id' => 331, 'province_id' => 21, 'name' => 'Kotawaringin Timur', 'type' => 'kabupaten'],
['id' => 332, 'province_id' => 21, 'name' => 'Lamandau', 'type' => 'kabupaten'],
['id' => 333, 'province_id' => 21, 'name' => 'Murung Raya', 'type' => 'kabupaten'],
['id' => 334, 'province_id' => 21, 'name' => 'Pulang Pisau', 'type' => 'kabupaten'],
['id' => 335, 'province_id' => 21, 'name' => 'Seruyan', 'type' => 'kabupaten'],
['id' => 336, 'province_id' => 21, 'name' => 'Sukamara', 'type' => 'kabupaten'],
['id' => 337, 'province_id' => 21, 'name' => 'Palangkaraya', 'type' => 'kota'],
['id' => 338, 'province_id' => 22, 'name' => 'Balangan', 'type' => 'kabupaten'],
['id' => 339, 'province_id' => 22, 'name' => 'Banjar', 'type' => 'kabupaten'],
['id' => 340, 'province_id' => 22, 'name' => 'Barito Kuala', 'type' => 'kabupaten'],
['id' => 341, 'province_id' => 22, 'name' => 'Hulu Sungai Selatan', 'type' => 'kabupaten'],
['id' => 342, 'province_id' => 22, 'name' => 'Hulu Sungai Tengah', 'type' => 'kabupaten'],
['id' => 343, 'province_id' => 22, 'name' => 'Hulu Sungai Utara', 'type' => 'kabupaten'],
['id' => 344, 'province_id' => 22, 'name' => 'Kota Baru', 'type' => 'kabupaten'],
['id' => 345, 'province_id' => 22, 'name' => 'Tabalong', 'type' => 'kabupaten'],
['id' => 346, 'province_id' => 22, 'name' => 'Tanah Bumbu', 'type' => 'kabupaten'],
['id' => 347, 'province_id' => 22, 'name' => 'Tanah Laut', 'type' => 'kabupaten'],
['id' => 348, 'province_id' => 22, 'name' => 'Tapin', 'type' => 'kabupaten'],
['id' => 349, 'province_id' => 22, 'name' => 'Banjar Baru', 'type' => 'kota'],
['id' => 350, 'province_id' => 22, 'name' => 'Banjarmasin', 'type' => 'kota'],
['id' => 351, 'province_id' => 23, 'name' => 'Berau', 'type' => 'kabupaten'],
['id' => 352, 'province_id' => 23, 'name' => 'Bulongan', 'type' => 'kabupaten'],
['id' => 353, 'province_id' => 23, 'name' => 'Kutai Barat', 'type' => 'kabupaten'],
['id' => 354, 'province_id' => 23, 'name' => 'Kutai Kartanegara', 'type' => 'kabupaten'],
['id' => 355, 'province_id' => 23, 'name' => 'Kutai Timur', 'type' => 'kabupaten'],
['id' => 356, 'province_id' => 23, 'name' => 'Malinau', 'type' => 'kabupaten'],
['id' => 357, 'province_id' => 23, 'name' => 'Nunukan', 'type' => 'kabupaten'],
['id' => 358, 'province_id' => 23, 'name' => 'Paser', 'type' => 'kabupaten'],
['id' => 359, 'province_id' => 23, 'name' => 'Penajam Paser Utara', 'type' => 'kabupaten'],
['id' => 360, 'province_id' => 23, 'name' => 'Tana Tidung', 'type' => 'kabupaten'],
['id' => 361, 'province_id' => 23, 'name' => 'Balikpapan', 'type' => 'kota'],
['id' => 362, 'province_id' => 23, 'name' => 'Bontang', 'type' => 'kota'],
['id' => 363, 'province_id' => 23, 'name' => 'Samarinda', 'type' => 'kota'],
['id' => 364, 'province_id' => 23, 'name' => 'Tarakan', 'type' => 'kota'],
['id' => 365, 'province_id' => 24, 'name' => 'Boalemo', 'type' => 'kabupaten'],
['id' => 366, 'province_id' => 24, 'name' => 'Bone Bolango', 'type' => 'kabupaten'],
['id' => 367, 'province_id' => 24, 'name' => 'Gorontalo', 'type' => 'kabupaten'],
['id' => 368, 'province_id' => 24, 'name' => 'Gorontalo Utara', 'type' => 'kabupaten'],
['id' => 369, 'province_id' => 24, 'name' => 'Pohuwato', 'type' => 'kabupaten'],
['id' => 370, 'province_id' => 24, 'name' => 'Gorontalo', 'type' => 'kota'],
['id' => 371, 'province_id' => 25, 'name' => 'Bantaeng', 'type' => 'kabupaten'],
['id' => 372, 'province_id' => 25, 'name' => 'Barru', 'type' => 'kabupaten'],
['id' => 373, 'province_id' => 25, 'name' => 'Bone', 'type' => 'kabupaten'],
['id' => 374, 'province_id' => 25, 'name' => 'Bulukumba', 'type' => 'kabupaten'],
['id' => 375, 'province_id' => 25, 'name' => 'Enrekang', 'type' => 'kabupaten'],
['id' => 376, 'province_id' => 25, 'name' => 'Gowa', 'type' => 'kabupaten'],
['id' => 377, 'province_id' => 25, 'name' => 'Jeneponto', 'type' => 'kabupaten'],
['id' => 378, 'province_id' => 25, 'name' => 'Luwu', 'type' => 'kabupaten'],
['id' => 379, 'province_id' => 25, 'name' => 'Luwu Timur', 'type' => 'kabupaten'],
['id' => 380, 'province_id' => 25, 'name' => 'Luwu Utara', 'type' => 'kabupaten'],
['id' => 381, 'province_id' => 25, 'name' => 'Maros', 'type' => 'kabupaten'],
['id' => 382, 'province_id' => 25, 'name' => 'Pangkajene Kepulauan', 'type' => 'kabupaten'],
['id' => 383, 'province_id' => 25, 'name' => 'Pinrang', 'type' => 'kabupaten'],
['id' => 384, 'province_id' => 25, 'name' => 'Selayar', 'type' => 'kabupaten'],
['id' => 385, 'province_id' => 25, 'name' => 'Sidenreng Rappang', 'type' => 'kabupaten'],
['id' => 386, 'province_id' => 25, 'name' => 'Sinjai', 'type' => 'kabupaten'],
['id' => 387, 'province_id' => 25, 'name' => 'Soppeng', 'type' => 'kabupaten'],
['id' => 388, 'province_id' => 25, 'name' => 'Takalar', 'type' => 'kabupaten'],
['id' => 389, 'province_id' => 25, 'name' => 'Tana Toraja', 'type' => 'kabupaten'],
['id' => 390, 'province_id' => 25, 'name' => 'Toraja Utara', 'type' => 'kabupaten'],
['id' => 391, 'province_id' => 25, 'name' => 'Wajo', 'type' => 'kabupaten'],
['id' => 392, 'province_id' => 25, 'name' => 'Makassar', 'type' => 'kota'],
['id' => 393, 'province_id' => 25, 'name' => 'Palopo', 'type' => 'kota'],
['id' => 394, 'province_id' => 25, 'name' => 'Pare-pare', 'type' => 'kota'],
['id' => 395, 'province_id' => 26, 'name' => 'Bombana', 'type' => 'kabupaten'],
['id' => 396, 'province_id' => 26, 'name' => 'Buton', 'type' => 'kabupaten'],
['id' => 397, 'province_id' => 26, 'name' => 'Buton Utara', 'type' => 'kabupaten'],
['id' => 398, 'province_id' => 26, 'name' => 'Kolaka', 'type' => 'kabupaten'],
['id' => 399, 'province_id' => 26, 'name' => 'Kolaka Utara', 'type' => 'kabupaten'],
['id' => 400, 'province_id' => 26, 'name' => 'Konawe', 'type' => 'kabupaten'],
['id' => 401, 'province_id' => 26, 'name' => 'Konawe Selatan', 'type' => 'kabupaten'],
['id' => 402, 'province_id' => 26, 'name' => 'Konawe Utara', 'type' => 'kabupaten'],
['id' => 403, 'province_id' => 26, 'name' => 'Muna', 'type' => 'kabupaten'],
['id' => 404, 'province_id' => 26, 'name' => 'Wakatobi', 'type' => 'kabupaten'],
['id' => 405, 'province_id' => 26, 'name' => 'Bau-bau', 'type' => 'kota'],
['id' => 406, 'province_id' => 26, 'name' => 'Kendari', 'type' => 'kota'],
['id' => 407, 'province_id' => 27, 'name' => 'Banggai', 'type' => 'kabupaten'],
['id' => 408, 'province_id' => 27, 'name' => 'Banggai Kepulauan', 'type' => 'kabupaten'],
['id' => 409, 'province_id' => 27, 'name' => 'Buol', 'type' => 'kabupaten'],
['id' => 410, 'province_id' => 27, 'name' => 'Donggala', 'type' => 'kabupaten'],
['id' => 411, 'province_id' => 27, 'name' => 'Morowali', 'type' => 'kabupaten'],
['id' => 412, 'province_id' => 27, 'name' => 'Parigi Moutong', 'type' => 'kabupaten'],
['id' => 413, 'province_id' => 27, 'name' => 'Poso', 'type' => 'kabupaten'],
['id' => 414, 'province_id' => 27, 'name' => 'Sigi', 'type' => 'kabupaten'],
['id' => 415, 'province_id' => 27, 'name' => 'Tojo Una-Una', 'type' => 'kabupaten'],
['id' => 416, 'province_id' => 27, 'name' => 'Toli Toli', 'type' => 'kabupaten'],
['id' => 417, 'province_id' => 27, 'name' => 'Palu', 'type' => 'kota'],
['id' => 418, 'province_id' => 28, 'name' => 'Bolaang Mangondow', 'type' => 'kabupaten'],
['id' => 419, 'province_id' => 28, 'name' => 'Bolaang Mangondow Se', 'type' => 'kabupaten'],
['id' => 420, 'province_id' => 28, 'name' => 'Bolaang Mangondow Ti', 'type' => 'kabupaten'],
['id' => 421, 'province_id' => 28, 'name' => 'Bolaang Mangondow Ut', 'type' => 'kabupaten'],
['id' => 422, 'province_id' => 28, 'name' => 'Kepulauan Sangihe', 'type' => 'kabupaten'],
['id' => 423, 'province_id' => 28, 'name' => 'Kepulauan Siau Tagul', 'type' => 'kabupaten'],
['id' => 424, 'province_id' => 28, 'name' => 'Kepulauan Talaud', 'type' => 'kabupaten'],
['id' => 425, 'province_id' => 28, 'name' => 'Minahasa', 'type' => 'kabupaten'],
['id' => 426, 'province_id' => 28, 'name' => 'Minahasa Selatan', 'type' => 'kabupaten'],
['id' => 427, 'province_id' => 28, 'name' => 'Minahasa Tenggara', 'type' => 'kabupaten'],
['id' => 428, 'province_id' => 28, 'name' => 'Minahasa Utara', 'type' => 'kabupaten'],
['id' => 429, 'province_id' => 28, 'name' => 'Bitung', 'type' => 'kota'],
['id' => 430, 'province_id' => 28, 'name' => 'Kotamobagu', 'type' => 'kota'],
['id' => 431, 'province_id' => 28, 'name' => 'Manado', 'type' => 'kota'],
['id' => 432, 'province_id' => 28, 'name' => 'Tomohon', 'type' => 'kota'],
['id' => 433, 'province_id' => 29, 'name' => 'Majene', 'type' => 'kabupaten'],
['id' => 434, 'province_id' => 29, 'name' => 'Mamasa', 'type' => 'kabupaten'],
['id' => 435, 'province_id' => 29, 'name' => 'Mamuju', 'type' => 'kabupaten'],
['id' => 436, 'province_id' => 29, 'name' => 'Mamuju Utara', 'type' => 'kabupaten'],
['id' => 437, 'province_id' => 29, 'name' => 'Polewali Mandar', 'type' => 'kabupaten'],
['id' => 438, 'province_id' => 30, 'name' => 'Buru', 'type' => 'kabupaten'],
['id' => 439, 'province_id' => 30, 'name' => 'Buru Selatan', 'type' => 'kabupaten'],
['id' => 440, 'province_id' => 30, 'name' => 'Kepulauan Aru', 'type' => 'kabupaten'],
['id' => 441, 'province_id' => 30, 'name' => 'Maluku Barat Daya', 'type' => 'kabupaten'],
['id' => 442, 'province_id' => 30, 'name' => 'Maluku Tengah', 'type' => 'kabupaten'],
['id' => 443, 'province_id' => 30, 'name' => 'Maluku Tenggara', 'type' => 'kabupaten'],
['id' => 444, 'province_id' => 30, 'name' => 'Maluku Tenggara Bara', 'type' => 'kabupaten'],
['id' => 445, 'province_id' => 30, 'name' => 'Seram Bagian Barat', 'type' => 'kabupaten'],
['id' => 446, 'province_id' => 30, 'name' => 'Seram Bagian Timur', 'type' => 'kabupaten'],
['id' => 447, 'province_id' => 30, 'name' => 'Ambon', 'type' => 'kota'],
['id' => 448, 'province_id' => 30, 'name' => 'Tual', 'type' => 'kota'],
['id' => 449, 'province_id' => 31, 'name' => 'Halmahera Barat', 'type' => 'kabupaten'],
['id' => 450, 'province_id' => 31, 'name' => 'Halmahera Selatan', 'type' => 'kabupaten'],
['id' => 451, 'province_id' => 31, 'name' => 'Halmahera Tengah', 'type' => 'kabupaten'],
['id' => 452, 'province_id' => 31, 'name' => 'Halmahera Timur', 'type' => 'kabupaten'],
['id' => 453, 'province_id' => 31, 'name' => 'Halmahera Utara', 'type' => 'kabupaten'],
['id' => 454, 'province_id' => 31, 'name' => 'Kepulauan Sula', 'type' => 'kabupaten'],
['id' => 455, 'province_id' => 31, 'name' => 'Pulau Morotai', 'type' => 'kabupaten'],
['id' => 456, 'province_id' => 31, 'name' => 'Ternate', 'type' => 'kota'],
['id' => 457, 'province_id' => 31, 'name' => 'Tidore Kepulauan', 'type' => 'kota'],
['id' => 458, 'province_id' => 32, 'name' => 'Fakfak', 'type' => 'kabupaten'],
['id' => 459, 'province_id' => 32, 'name' => 'Kaimana', 'type' => 'kabupaten'],
['id' => 460, 'province_id' => 32, 'name' => 'Manokwari', 'type' => 'kabupaten'],
['id' => 461, 'province_id' => 32, 'name' => 'Maybrat', 'type' => 'kabupaten'],
['id' => 462, 'province_id' => 32, 'name' => 'Raja Ampat', 'type' => 'kabupaten'],
['id' => 463, 'province_id' => 32, 'name' => 'Sorong', 'type' => 'kabupaten'],
['id' => 464, 'province_id' => 32, 'name' => 'Sorong Selatan', 'type' => 'kabupaten'],
['id' => 465, 'province_id' => 32, 'name' => 'Tambrauw', 'type' => 'kabupaten'],
['id' => 466, 'province_id' => 32, 'name' => 'Teluk Bintuni', 'type' => 'kabupaten'],
['id' => 467, 'province_id' => 32, 'name' => 'Teluk Wondama', 'type' => 'kabupaten'],
['id' => 468, 'province_id' => 32, 'name' => 'Sorong', 'type' => 'kota'],
['id' => 469, 'province_id' => 33, 'name' => 'Merauke', 'type' => 'kabupaten'],
['id' => 470, 'province_id' => 33, 'name' => 'Jayawijaya', 'type' => 'kabupaten'],
['id' => 471, 'province_id' => 33, 'name' => 'Nabire', 'type' => 'kabupaten'],
['id' => 472, 'province_id' => 33, 'name' => 'Kepulauan Yapen', 'type' => 'kabupaten'],
['id' => 473, 'province_id' => 33, 'name' => 'Biak Numfor', 'type' => 'kabupaten'],
['id' => 474, 'province_id' => 33, 'name' => 'Paniai', 'type' => 'kabupaten'],
['id' => 475, 'province_id' => 33, 'name' => 'Puncak Jaya', 'type' => 'kabupaten'],
['id' => 476, 'province_id' => 33, 'name' => 'Mimika', 'type' => 'kabupaten'],
['id' => 477, 'province_id' => 33, 'name' => 'Boven Digoel', 'type' => 'kabupaten'],
['id' => 478, 'province_id' => 33, 'name' => 'Mappi', 'type' => 'kabupaten'],
['id' => 479, 'province_id' => 33, 'name' => 'Asmat', 'type' => 'kabupaten'],
['id' => 480, 'province_id' => 33, 'name' => 'Yahukimo', 'type' => 'kabupaten'],
['id' => 481, 'province_id' => 33, 'name' => 'Pegunungan Bintang', 'type' => 'kabupaten'],
['id' => 482, 'province_id' => 33, 'name' => 'Tolikara', 'type' => 'kabupaten'],
['id' => 483, 'province_id' => 33, 'name' => 'Sarmi', 'type' => 'kabupaten'],
['id' => 484, 'province_id' => 33, 'name' => 'Keerom', 'type' => 'kabupaten'],
['id' => 485, 'province_id' => 33, 'name' => 'Waropen', 'type' => 'kabupaten'],
['id' => 486, 'province_id' => 33, 'name' => 'Jayapura', 'type' => 'kabupaten'],
['id' => 487, 'province_id' => 33, 'name' => 'Deiyai', 'type' => 'kabupaten'],
['id' => 488, 'province_id' => 33, 'name' => 'Dogiyai', 'type' => 'kabupaten'],
['id' => 489, 'province_id' => 33, 'name' => 'Intan Jaya', 'type' => 'kabupaten'],
['id' => 490, 'province_id' => 33, 'name' => 'Lanny Jaya', 'type' => 'kabupaten'],
['id' => 491, 'province_id' => 33, 'name' => 'Mamberamo Raya', 'type' => 'kabupaten'],
['id' => 492, 'province_id' => 33, 'name' => 'Mamberamo Tengah', 'type' => 'kabupaten'],
['id' => 493, 'province_id' => 33, 'name' => 'Nduga', 'type' => 'kabupaten'],
['id' => 494, 'province_id' => 33, 'name' => 'Puncak', 'type' => 'kabupaten'],
['id' => 495, 'province_id' => 33, 'name' => 'Supiori', 'type' => 'kabupaten'],
['id' => 496, 'province_id' => 33, 'name' => 'Yalimo', 'type' => 'kabupaten'],
['id' => 497, 'province_id' => 33, 'name' => 'Jayapura', 'type' => 'kota'],
['id' => 498, 'province_id' => 34, 'name' => 'Bulungan', 'type' => 'kabupaten'],
['id' => 499, 'province_id' => 34, 'name' => 'Malinau', 'type' => 'kabupaten'],
['id' => 500, 'province_id' => 34, 'name' => 'Nunukan', 'type' => 'kabupaten'],
['id' => 501, 'province_id' => 16, 'name' => 'Wahyudi', 'type' => 'kota'],
['id' => 502, 'province_id' => 21, 'name' => 'Kotawaringin Timur', 'type' => 'kabupaten'],
['id' => 503, 'province_id' => 23, 'name' => 'Tanjungredep', 'type' => 'kabupaten'],
['id' => 504, 'province_id' => 12, 'name' => 'Trucking', 'type' => 'kota'],
['id' => 505, 'province_id' => 11, 'name' => 'Cimone - Cibitung', 'type' => 'kabupaten'],
['id' => 506, 'province_id' => 13, 'name' => 'Kota Cikarang', 'type' => 'kota']
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cities');
    }
}
